[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/hairyhenderson/toml"
  branch = "support-map-interface-keys"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-sockaddr"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "master"
